// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_amateur_ball = "CgkIhfKEuqMCEAIQAg"; // <GPGSID>
        public const string achievement_breaker = "CgkIhfKEuqMCEAIQCw"; // <GPGSID>
        public const string achievement_no_life = "CgkIhfKEuqMCEAIQBw"; // <GPGSID>
        public const string achievement_stop_playing = "CgkIhfKEuqMCEAIQBg"; // <GPGSID>
        public const string achievement_360_destruction = "CgkIhfKEuqMCEAIQDA"; // <GPGSID>
        public const string achievement_cool_skinned = "CgkIhfKEuqMCEAIQDw"; // <GPGSID>
        public const string achievement_are_you_ralph = "CgkIhfKEuqMCEAIQDQ"; // <GPGSID>
        public const string achievement_fashion_victim = "CgkIhfKEuqMCEAIQEA"; // <GPGSID>
        public const string achievement_swag = "CgkIhfKEuqMCEAIQDg"; // <GPGSID>
        public const string achievement_big_boss = "CgkIhfKEuqMCEAIQAQ"; // <GPGSID>
        public const string achievement_investor = "CgkIhfKEuqMCEAIQCQ"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIhfKEuqMCEAIQEQ"; // <GPGSID>
        public const string achievement_unemployed = "CgkIhfKEuqMCEAIQCA"; // <GPGSID>
        public const string achievement_nice_try = "CgkIhfKEuqMCEAIQBQ"; // <GPGSID>
        public const string achievement_master_ball = "CgkIhfKEuqMCEAIQBA"; // <GPGSID>
        public const string achievement_pro_ball = "CgkIhfKEuqMCEAIQAw"; // <GPGSID>
        public const string achievement_rich_guy = "CgkIhfKEuqMCEAIQCg"; // <GPGSID>

}

