// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_amateur_ball = "CgkIj8WBnNYQEAIQAg"; // <GPGSID>
        public const string achievement_breaker = "CgkIj8WBnNYQEAIQCw"; // <GPGSID>
        public const string achievement_no_life = "CgkIj8WBnNYQEAIQBw"; // <GPGSID>
        public const string achievement_stop_playing = "CgkIj8WBnNYQEAIQBg"; // <GPGSID>
        public const string achievement_360_destruction = "CgkIj8WBnNYQEAIQDA"; // <GPGSID>
        public const string achievement_cool_skinned = "CgkIj8WBnNYQEAIQDw"; // <GPGSID>
        public const string achievement_are_you_ralph = "CgkIj8WBnNYQEAIQDQ"; // <GPGSID>
        public const string achievement_fashion_victim = "CgkIj8WBnNYQEAIQEA"; // <GPGSID>
        public const string achievement_swag = "CgkIj8WBnNYQEAIQDg"; // <GPGSID>
        public const string achievement_big_boss = "CgkIj8WBnNYQEAIQEQ"; // <GPGSID>
        public const string achievement_investor = "CgkIj8WBnNYQEAIQCQ"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIj8WBnNYQEAIQAQ"; // <GPGSID>
        public const string achievement_unemployed = "CgkIj8WBnNYQEAIQCA"; // <GPGSID>
        public const string achievement_nice_try = "CgkIj8WBnNYQEAIQBQ"; // <GPGSID>
        public const string achievement_master_ball = "CgkIj8WBnNYQEAIQBA"; // <GPGSID>
        public const string achievement_pro_ball = "CgkIj8WBnNYQEAIQAw"; // <GPGSID>
        public const string achievement_rich_guy = "CgkIj8WBnNYQEAIQCg"; // <GPGSID>

}

